name: Build Chatbot Index
on:
  workflow_dispatch:
jobs:
  build-index:
    runs-on: ubuntu-latest
    timeout-minutes: 15 
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 PyMuPDF
          pip install sentence-transformers faiss-cpu
      - name: Run the Indexer script
        run: python indexer.py
      - name: Commit and push the new index files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          # --- THIS LINE IS UPDATED to save the new .json file ---
          git add document_index.faiss document_mapping.json
          git diff-index --quiet HEAD || git commit -m "Build/update chatbot index files"
          git push

